version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=bitnami
    volumes:
      - 'mariadb_data:/bitnami'

  adminer:
      image: adminer
      restart: always
      ports:
          - 40003:8080
volumes:
  mariadb_data:
    driver: local
