###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  memcached:
    image: 'memcached:alpine'

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '24002:8025'

  redis:
    image: 'redis:alpine'

  mysql:
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=gundo
      - MYSQL_DATABASE=gundo
      - MYSQL_USER=gundo
      - MYSQL_PASSWORD=gundo
    ports:
      - '24003:3306'

  mariadb:
    image: 'mariadb:10.6'
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=gundo
      - MYSQL_DATABASE=gundo
      - MYSQL_USER=gundo
      - MYSQL_PASSWORD=gundo
    ports:
      - '24004:3306'

  postgres:
    image: 'postgres:11.1-alpine'
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - POSTGRES_USER=gundo
      - POSTGRES_PASSWORD=gundo
      - POSTGRES_DB=gundo
    ports:
      - '24005:5432'

  elasticsearch:
    image: 'elasticsearch:6.5.4'

  clickhouse:
    image: 'yandex/clickhouse-server:latest'


  webserver:
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '24001:80'

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8081:40000"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: magento

  volumes:


